baseURL = "https://pepegar.com/"

languageCode = "en-us"
title = "pepegar.com"
theme = "paperesque"

# Code Highlight
pygmentsstyle = "monokailight"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

staticDir = ['static']

[[params.topmenu]]
  name = "blog"
  url = "posts"

[[params.topmenu]]
  name = "rss"
  url = "posts/index.xml"

[params]
  mode="auto" # color-mode → light,dark or auto
  featherIconsCDN=true
  subtitle = "Rants about computers"
  hideMadeWithLine = true
    

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    noClasses = false
