baseURL = "https://pepegar.com/"

languageCode = "en-us"
title = "pepegar"
theme = "hugo-pepegar"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

staticDir = ['static']

[params]
  customCss = [
    "css/sidenote.css",
    "css/custom.css",
    "css/syntax.css",
  ]
	mode="auto" # color-mode → light,dark or auto
	featherIconsCDN=true
	subtitle = "Rants about computers"
  hideMadeWithLine = true
    
[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/pepegar"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/_pepegar"

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    noClasses = false
