[build]
publish = "public"
command = "hugo --verbose --gc --minify --enableGitInfo"

[context.production.environment]
HUGO_VERSION = "0.58.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
